# Generated by Django 5.2.1 on 2025-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='medico',
        ),
        migrations.AddField(
            model_name='medico',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='my_app.horario'),
        ),
        migrations.AlterModelTable(
            name='citamedica',
            table='sgm_t_cita_medica',
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='sgm_p_ciudad',
        ),
        migrations.AlterModelTable(
            name='consultorio',
            table='sgm_m_consultorio',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='sgm_m_empleado',
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table='sgm_p_especialidad',
        ),
        migrations.AlterModelTable(
            name='horario',
            table='sgm_p_horario',
        ),
        migrations.AlterModelTable(
            name='medico',
            table='sgm_m_medico',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='sgm_m_paciente',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='sgm_p_rol',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='sgm_p_ubicacion',
        ),
    ]
