# Generated by Django 5.2.1 on 2025-07-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_horario_medico_medico_horarios_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='sgm_m_menu',
        ),
        migrations.AlterModelTable(
            name='module',
            table='sgm_m_module',
        ),
    ]
